name: CI

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-versions:
    name: Test Rust ${{ matrix.rust }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # if you have an MSRV, you can of course include it here too.
        rust: [stable, beta, nightly]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust}}
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --all-features
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --no-default-features

  rustfmt:
    name: Verify code formatting
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt     
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check --verbose

  clippy:
    name: Lint with Clippy
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -Dwarnings
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
      
  codecov-tarpaulin:
    name: Generate code coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: actions-rs/tarpaulin@v0.1
        with:
          args: --all-features
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
